### ISSUE TITLE
New version of UnityActivateLicenseTask 1.0.41 fails with "[error]Input required: activationMode"

### ISSUE THREAD

**Issue by RossWlodarczyk** [Dinomite-Studios/unity-azure-pipelines-tasks#163]
Hi,
Over the weekend (worked 8/1/2021 not on 11/1/2021) the UnityActivateLicenseTask started failing with

**Input required: activationMode
##[error]Input required: activationMode**

We can't see where to specify the "activationMode" or what the valid values are. We reverted to version "1.0.27" and UnityActivateLicenseTask works fine. See full output below.

Starting: Activate Unity License (Single Seat)
==============================================================================
Task         : Unity Activate License
Description  : Activates a Unity license on the agent.
Version      : 1.0.41
Author       : Dinomite Studios
Help         : Use this task to activate a Unity Plus/Pro license on the executing agent machine. [More Information](https://unitydevops.com/docs/unity-activate-license-task)
==============================================================================
Input required: activationMode
##[error]Input required: activationMode
Finishing: Activate Unity License (Single Seat)

**Comment by davidisaza** [comment]
I am currently running into the same issue. Is there any chance you could give me an examle of your YAML that shows how to download that specific version "1.0.27".

My YAML:
# Activate the Unity license (In theory, should deactivate the licence after use!):
  - task: UnityActivateLicenseTask@1
    inputs:
      username: '$(unity.username)'
      password: '$(unity.password)'
      serial: '$(unity.serialkey)'
      unityEditorsPathMode: 'unityHub'
      unityProjectPath: '$(unity.projectPath)'

Thank you

**Comment by FejZa** [comment]
Thanks everyone, looking into it

**Comment by FejZa** [comment]
A fix has been released for this issue, make sure your DevOps updated to v2.8.2.

**Comment by RossWlodarczyk** [comment]
> I am currently running into the same issue. Is there any chance you could give me an examle of your YAML that shows how to download that specific version "1.0.27".
> 
> My YAML:
> 
> # Activate the Unity license (In theory, should deactivate the licence after use!):
> * task: UnityActivateLicenseTask@1
>   inputs:
>   username: '$(unity.username)'
>   password: '$(unity.password)'
>   serial: '$(unity.serialkey)'
>   unityEditorsPathMode: 'unityHub'
>   unityProjectPath: '$(unity.projectPath)'
> 
> Thank you

You can specify the specific version in the task name@version, see below.

- task: UnityActivateLicenseTask@1.0.27

**Comment by RossWlodarczyk** [comment]
> A fix has been released for this issue, make sure your DevOps updated to v2.8.2.

Thanks, will test and will let you know how we go.

**Comment by davidisaza** [comment]
Hello Team,
We have Updated our Devops to v2.8.2, but we are still getting the same issue: One thing I noticed is that the Unity Activate License version is still the same 1.0.41. Another thing is that if there is a new parameter "activationMode" there is no documentation on it on the website.

[debug]Evaluating condition for step: 'UnityActivateLicenseTask'
[debug]Evaluating: SucceededNode()
[debug]Evaluating SucceededNode:
[debug]=> True
[debug]Result: True
[section]Starting: UnityActivateLicenseTask
==============================================================================
Task         : Unity Activate License
Description  : Activates a Unity license on the agent.
Version      : 1.0.41
Author       : Dinomite Studios
Help         : Use this task to activate a Unity Plus/Pro license on the executing agent machine. [More Information](https://unitydevops.com/docs/unity-activate-license-task)
==============================================================================
[debug]agent.TempDirectory=C:\agent\_work\_temp
[debug]loading inputs and endpoints
[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
[debug]loading INPUT_PASSWORD
[debug]loading INPUT_SERIAL
[debug]loading INPUT_UNITYEDITORSPATHMODE
[debug]loading INPUT_UNITYPROJECTPATH
[debug]loading INPUT_USERNAME
[debug]loading SECRET_SYSTEM_ACCESSTOKEN
[debug]loading SECRET_UNITY_PASSWORD
[debug]loading SECRET_UNITY_SERIALKEY
[debug]loading SECRET_UNITY_USERNAME
[debug]loaded 12
[debug]Agent.ProxyUrl=undefined
[debug]Agent.CAInfo=undefined
[debug]Agent.ClientCert=undefined
[debug]Agent.SkipCertValidation=undefined
[debug]check path : C:\agent\_work\_tasks\UnityActivateLicenseTask_13159b9a-b7ba-4977-922c-2b5cb63c90df\1.0.41\task.json
[debug]adding resource file: C:\agent\_work\_tasks\UnityActivateLicenseTask_13159b9a-b7ba-4977-922c-2b5cb63c90df\1.0.41\task.json
[debug]system.culture=en-US
[debug]username=***
[debug]password=***
Input required: activationMode
[debug]task result: Failed
[error]Input required: activationMode
[debug]Processed: ##vso[task.issue type=error;]Input required: activationMode
[debug]Processed: ##vso[task.complete result=Failed;]Input required: activationMode
[section]Finishing: UnityActivateLicenseTask

Please note to not close this untli we actually get it working.

Thanks

**Comment by RossWlodarczyk** [comment]
We have it working, its picking up version 1.0.42 as below. Version 1.0.41 is the broken version, you aren't picking up the right version. Maybe try referencing version 1.0.42 explicitly => "- task: UnityActivateLicenseTask@1.0.42"


==============================================================================
Task         : Unity Activate License
Description  : Activates a Unity license on the agent.
Version      : 1.0.42
Author       : Dinomite Studios
Help         : Use this task to activate a Unity Plus/Pro license on the executing agent machine. [More Information](https://unitydevops.com/docs/unity-activate-license-task)
==============================================================================

**Comment by FejZa** [comment]
Hello @davidisaza,

please try re-installing the extension on your organization if nothing helps. 1.0.41 is the broken version. You need to have 1.0.42 for the fix to work. Also please note that `activationMode` does not need documentation as it is not a feature and not supposed to exist at all. It just got merged in 1.0.41 incorrectly.

I will reopen the issue until you confirmed you have 1.0.42 working.

**Comment by FejZa** [comment]
@davidisaza any news on this? Were you able to update your task?

**Comment by davidisaza** [comment]
Hello,
After more testing and cleaning up the agent the system finally downloaded the correct 1.0.42 version. I am sorry for the troubles and thanks for getting this fixed so quickly. 

David I.

**Comment by FejZa** [comment]
Glad you got it fixed!
